#!/bin/sh


case "$1" in
  start)
	losetup /dev/loop0 /dev/mtdblock5
	mkswap /dev/loop0
	swapon /dev/loop0
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
