#!/bin/sh


case "$1" in
  start)
        DISPLAY=:0 xterm &
        ;;
  stop)
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

